### ISSUE TITLE
Arduino compatiblilty ?

### ISSUE THREAD

**Issue by RandoSY** [jacdac/jacdac-ts#11]
Hello,

Are you anticipating there will be a way for simple Arduino controllers to participate in the mesh/web?

Thanks

R.

**Comment by jamesadevine** [comment]
Hi @RandoSY thanks for your query :smile:

Right now there is no independent, pure C JACDAC library that others can use, it still needs to be written.

The only JACDAC libraries available right now are the typescript version contained in this repository, and the [JACDAC library from CODAL](https://github.com/lancaster-university/codal-core/tree/master/source/JACDAC).

If you mean "simple Arduino microcontrollers" like the Arduino Zero, then you can use the samd21 based boards in https://maker.makecode.com to run JACDAC for now. A library that can run on Atmega328p based arduinos would require a significant amount of work and would likely only be able to support a subset of JACDAC features.

Any help to create a C library would be greatly appreciated as I'm somewhat starved of time :smile:

**Comment by RandoSY** [comment]
Thanks so much for the consideration of your prompt reply.

I did download the repo "codal-core" and focused my attention on these two files.

1. JDService.cpp

2. JDPhysical.cpp

Am I looking under the correct rock? I think your spot on regarding the basic 328p being a little short of resources, but I have just about every other SAMD21 resource imaginable to work with other wise, and maybe a reduced command set would make sense in a lot of simple situations.  Have you generated any documentation that discusses the JACDAC protocol language independent yet?

I can see from the C++ (which is quite beautiful by the way) that there is a bit of negotiation and waiting,  outright cooperation if you will, required to send data bi-bidirectionally down one wire. Kind of reminds me of Ethernet,  just haven't quite noodled out the strategy yet. 

I think the idea of the stereo jack is brilliant, very robust and secure connection. PICAxe has been using if  for years as serial connector and it works great.

**Comment by tballmsft** [comment]
See https://jacdac.org for the specification.

**Comment by jamesadevine** [comment]
> I did download the repo "codal-core" and focused my attention on these two files.
> 
> 1. JDService.cpp
> 2. JDPhysical.cpp
>
> Am I looking under the correct rock? I think you're spot on regarding the basic 328p being a little short of resources, but I have just about every other SAMD21 resource imaginable to work with other wise, and maybe a reduced command set would make sense in a lot of simple situations. 

In the world of the multi-repo, there are many rocks :smile: You have overturned the abstract protocol implementation in JDPhysicalLayer.cpp. The physical layer is responsible for transmitting and receiving packets on the bus and handling any error conditions that may occur. JDService.cpp is the driver model for jacdac services.

With regard to porting jacdac to Arduino, the control layer contained in JACDAC/control would consume the most time. Specifically, the [Control Service](https://github.com/lancaster-university/codal-core/blob/master/inc/JACDAC/control/JDControlService.h), which routes packets received on the physical layer to services running on the device.

> Have you generated any documentation that discusses the JACDAC protocol, language independent yet?

As @tballmsft mentioned, the language agnostic specification is available at https://jacdac.org/specification 

> I can see from the C++ (which is quite beautiful by the way) that there is a bit of negotiation and waiting, outright cooperation if you will, required to send data bi-bidirectionally down the one wire. Kind of reminds me of Ethernet, just haven't quite noodled out the strategy yet.

First of all, thank you, I primarily try to make it readable :smile: I was trained by the master  programmer @finneyj 

 Devices do operate UART on a single wire, achievable on high end microcontrollers such as the SAMD21 (a single wire serial implementation is available in [this repository](https://github.com/lancaster-university/codal-samd/blob/master/src/ZSingleWireSerial.cpp) for the samd21/samd51). To indicate that a device is transmitting (bus arbitration) the bus is driven lo for 1 byte at the upcoming baud rate (10us for 1mbaud, 80us for 125 kbaud). A state machine is provided on the specification page that details possible error states that may occur on the bus.

> I think the idea of the stereo jack is brilliant, very robust and secure connection. PIC Axe has been using if for years as serial connector, and it works great.

Oh really? We by no means thought it was a novel idea, but didn't realise it was so widely used. Would you be able to share a link about its use?

Where did you hear about JACDAC by the way? :smile:

**Comment by jamesadevine** [comment]
p.s. @RandoSY We have detail in the spec to incorporate small microcontrollers in a transmit only capacity: https://jacdac.org/specification/#transmit-only-devices

**Comment by RandoSY** [comment]
Hi James,

PIC Axe is an interesting project, very effective in application...

http://picaxe.hobbizine.com/usb.html

I did note the section in the spec about supporting 4/8 bit ucontrollers, and one Github folder for a section on PIC12 that hadn't had any work contributed yet. PIC12 would be a good choice as the clock speed it high, generous memory, and an excellent tool, and code base. The ATtiny-1 series also would be interesting. 

As I review your excellent specification, I was quite, quite surprised to see the passing resemblance to Bluetooth Low Energy, can you imagine a say when you lose the wire, and go to RF?

Let me review your recommendations over the weekend, I'm wondering what would be the cheapest and most expeditious way to got a "master" (sorry old habits die hard) on my bench so I could look at getting a logic analyzer catching the traffic so I have something to work with? 

Ready built would be nice, but I could cook a pcb/smd if I had to. My construction skills are terrible but I always seem to find someone to help me... :)

Best,

R.

**Comment by jamesadevine** [comment]
> Hi James,
> 
> PIC Axe is an interesting project, very effective in application...
> 
> http://picaxe.hobbizine.com/usb.html

Yes, I'm familiar with the project, I was just unaware about the USB -> audio jack converter!

> I did note the section in the spec about supporting 4/8 bit ucontrollers, and one Github folder for a section on PIC12 that hadn't had any work contributed yet. PIC12 would be a good choice as the clock speed it high, generous memory, and an excellent tool, and code base. The ATtiny-1 series also would be interesting.

We spent many hours deliberating over this selection. It also allows us to move from pic12 to pic10 in the future (we'd have to bit bang UART). 

> As I review your excellent specification, I was quite, quite surprised to see the passing resemblance to Bluetooth Low Energy, can you imagine a say when you lose the wire, and go to RF?

JACDAC was created using past experiences in the world of embedded systems. I spent some time on BLE when I worked on the [microbit-dal](https://github.com/lancaster-university/microbit-dal) (although not nearly as much as @finneyj) and some time looking at USB. So in many ways, JACDAC is some composition of the two... That said, it certainly wasn't a conscious composition, and many design decisions were made purely because of how the stack evolved.

We've already extended JACDAC to USB, and thus to the browser (thanks to WebUSB!). Other than the complexity of the BLE protocol itself, I see no reason why JACDAC can't be extended to BLE.

> Let me review your recommendations over the weekend, I'm wondering what would be the cheapest and most expeditious way to got a "master" (sorry old habits die hard) on my bench so I could look at getting a logic analyzer catching the traffic so I have something to work with?

I know what you mean... it has taken me some time to adjust, but I believe overall it is a positive change. Send me a schematic of one of the samd21 boards you have an I'll produce a hex/bin for you:

j.devine@lancaster.ac.uk

**Comment by RandoSY** [comment]
Hi James,

To directly answer your earlier question I found JACDAC from a link a friend sent me on Makecode Arcade. 

He knows I have an interest in education, my graduate degree is in STEM education and I use to volunteer teaching robotics and CS in local community workshops. 

I had previously been somewhat aloof with/using the drag and drop programming paradigm because I felt it might be a somewhat abstracted from the hardware, and was antithetical to my start at the lowest level possible, and proceed from there approach. Actually I had had a negative experience with the Micro:bit re. hardware failures, and had managed to derail myself by experimenting with changing the debug processor over to Segger from CMSIS-DAP and then just work inside Keil and the nRF51822 as a standard ARM SoC.  

Unfortunately the Micro:Bit has the 'QA' version of the nRF51822, vs. the 'QC' so the low-ram (16k) precludes running a lot of the logical add-ons to building a learning trajectory from C to Python and Javascript Espruino, so when I advanced to using the nRF5832 I just left it in the drawer. I've been struggling with understanding BLE for a year now, especially on how to best communicate to someone else how, and most importantly why to use it. The high end facilities like Circuity Python really lower the bar on getting started with the technology.

Typically short sighted, I think, the simple fact is that there have been several successful overtures locally that take advantage of the web browser/msd usb mass storage flash convenience of Makecode to run easily in a community college computer lab. Nothing to install, click the link, ready to go. "When in Rome, do as the Romans."

So herein lies the dilemma, if as an educator you ride the easy horse, and start the students with a very high level programming language, all goes well until you forced by any number of requirements, to look under the covers, at the machine there within. The is in opposition to any other subject that can be approached historically, and logically extrapolated from first principles. I have taught many a Science subject in exactly that same way. 

Your JACDAC project is a window into low-level programming, peer networking, and resource sharing that can organically be applied to Makecode curricula, that would serve as a natural introduction/evolution to low level programing as a necessity to getting it working.  The fact that it shouldn't be very expensive to do is another real plus. I am very much a proponent of inquiry, and constructionist learning theory, I've seen it be very effective, but you need to be careful in guiding the process in a way that best serves the long term interest of the students. Sooner or later you need to get them looking at the 1/0 transition  as a waveform, and convincing them, "well, that's all there is" and given that resource how to we move forward? Actually that works with Kindergarten kids, I switch off the lights and they call out 1 and 0, until we've built simple works like CAT and DOG in ascii. 

As I mentioned earlier I have a collection of SAMD21 dev boards to evaluate. Let's do the Trinket M0, as it will be expeditious to add more "beads" to the "string". 

![adafruit_products_schem](https://user-images.githubusercontent.com/609947/59510801-a06e8100-8e82-11e9-914e-d4a6e0b40be5.png)
 
***

If you haven't had a chance to look at GCB (Great Cow Basic) take a look ...
https://sourceforge.net/p/gcbasic/discussion/579126/thread/b89fc419/

**Comment by jamesadevine** [comment]
> So herein lies the dilemma, if as an educator you ride the easy horse, and start the students with a very high level programming language, all goes well until you forced by any number of requirements, to look under the covers, at the machine there within. The is in opposition to any other subject that can be approached historically, and logically extrapolated from first principles. I have taught many a Science subject in exactly that same way.
>
> Your JACDAC project is a window into low-level programming, peer networking, and resource sharing that can organically be applied to/from Makecode curricula, that could serve as a natural introduction/evolution to low level programing as a necessity to getting it working. The fact that it shouldn't be very expensive to do is another real plus.

That's a very interesting point of view, and one I think we've been thinking about too. 

> As I mentioned earlier I have a collection of SAMD21 dev boards to evaluate. Let's do the Trinket M0 Express, as it will be expeditious to add more "beads" to the "string" later.
> 
> https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/downloads
> 
> ![adafruit_products_schem](https://user-images.githubusercontent.com/609947/59510801-a06e8100-8e82-11e9-914e-d4a6e0b40be5.png)

Oh that's an easy one, open [this MakeCode project](https://makecode.com/_2JJAhKX7CgC2) and copy to your trinket. If you probe the TX pin, you should see some JACDAC! 

> If you haven't had a chance to look at GCB (Great Cow Basic) take a look ... very open and inviting community.
> 
> https://sourceforge.net/p/gcbasic/discussion/579126/thread/b89fc419/

Will take a look! :smile:

**Comment by RandoSY** [comment]
OK, was excited to be able to compile the example you sent me on my Android tablet, and email myself the "executable", just a simple matter to double tap the Trinket M0 to get to the native  mass storage boot loader, and drag an drop the *.uf2 file to the Trinket. Quite a new experience for me!

Next step will be to get something to trace the activity on the TX pin #7? (Sercom0.2). 

I should imagine the real trick would to put several trinkets on the same serial wire, and really exercise the
protocol the way it is intended....

Thanks again for the consideration of your valuable time.

**Comment by RandoSY** [comment]
Getting there ...

![20190616_112406](https://user-images.githubusercontent.com/609947/59566201-ae5f0600-902a-11e9-9d8c-041a6291e9b0.jpg)

**Comment by jamesadevine** [comment]
I believe I tested the protocol on the trinket last week, but do let me know if you run into problems... The cool thing is that you write services in typescript :smile: Also, if you have web usb go to https://jacdac.org/debug and see if your device appears (I can't remember if we enabled web usb in makecode builds). If it doesn't I can attach a uf2 for the trinket that does

**Comment by RandoSY** [comment]
Quite a bit to learn here, but I think I see enough of the expected activity to put some other devices on the wire, and look for the correct behavior...

![2019-06-16 18_12_56-Greenshot](https://user-images.githubusercontent.com/609947/59570220-be92d780-9062-11e9-8473-4f7224ffb2ca.png)

**Comment by jamesadevine** [comment]
@RandoSY looks good to me :smile:

**Comment by RandoSY** [comment]
I would like to see the version of the app that will work with the web-usb powered  debugger. 

Thanks!

**Comment by jamesadevine** [comment]
@RandoSY I'll check my end, but are you sure it doesn't already work?

**Comment by RandoSY** [comment]
Hi James,

You make a very good point, basically I just fired up the app in Chrome and let if try and find something, which in fact is kinda silly in that I shouldn't think the virtual com port wouldn't be nearly "immediate" enough to run this very specific protocol.  I was able (I think) to identify some SAMD21 code that was using Sercom0 dma to deal with the rigors of capturing the 1mb serial stream for later analysis. 

I've seen the ARM M0 peripheral (A2D) --> to DMA work before in an ultrasonic hematocrit measurement device, and it was critical to capturing the fleeting signal form the detector. What's going on with web-usb is quite another matter I would assume, just something else I need to get up to speed on. 

This "browser" as OS, javascript, typescript, is frankly completely **new to me** :)

**Comment by jamesadevine** [comment]
> You make a very good point, basically I just fired up the app in Chrome and let if try and find something, which in fact is kinda silly in that I shouldn't think the virtual com port wouldn't be nearly "immediate" enough to run this very specific protocol.

It is if the JACDAC usb driver is running!! :smile: did no devices appear when you visited  https://jacdac.org/debug and hit the connect button?

**Comment by jamesadevine** [comment]
[maker-Untitled (33).uf2.zip](https://github.com/jacdac/jacdac-ts/files/3303031/maker-Untitled.33.uf2.zip)
The attached uf2 should appear in Chrome on mac / linux. We have a few teething issues with windows...

**Comment by RandoSY** [comment]
Got it, thanks!

**Comment by RandoSY** [comment]
Do these VID/PID's look right?

[  486.842176] usb 2-2: new full-speed USB device number 3 using ohci-pci
[  487.202841] usb 2-2: New USB device found, **idVendor=03eb, idProduct=2402**
[  487.202845] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  487.202847] usb 2-2: Product: Trinket M0 (app)
[  487.202849] usb 2-2: Manufacturer: Trinket M0 (app)
[  487.202850] usb 2-2: SerialNumber: 1800921092

**Comment by RandoSY** [comment]
I trudged through some code: here's my udev rule:

SUBSYSTEM=="usb", ATTR{idVendor}=="03eb", ATTR{idProduct}=="2402", GROUP="plugdev"

This is working via an Oracle VirtualBox VM, which I've worked on quite a bit to get the usb forwarding solid as possible. 

![Working connect via VM](https://user-images.githubusercontent.com/609947/59729190-4ddaef00-920b-11e9-9025-b75811ac84ba.JPG)

![Connected!](https://user-images.githubusercontent.com/609947/59729196-53d0d000-920b-11e9-9777-8e0a965d59f4.JPG)

**Comment by RandoSY** [comment]
I'm see
![Should be able to see all!!!](https://user-images.githubusercontent.com/609947/59729640-40266900-920d-11e9-9978-2aea14967521.JPG)
ing the regular query on the bus ...

**Comment by RandoSY** [comment]
Is it complicated to build my own "web-usb debug friendly" trinket apps? I'd like to get a couple more trinkets on the "party line" and experiment with designing my own services, etc. I can usually muddle through most things with a little guidance. :)

**Comment by jamesadevine** [comment]
Wow, looks great! Nice work 😄 

You can choose to develop in C/C++ or MakeCode by following the instructions [here](https://jacdac.org/getting-started/).

For a web usb friendly build via MakeCode, there's a secret toggle in "Project Settings":

<img width="1329" alt="Screenshot 2019-06-19 at 10 52 53" src="https://user-images.githubusercontent.com/4742697/59755809-7e10a500-9280-11e9-939a-364ea566b03e.png">
<img width="1258" alt="Screenshot 2019-06-19 at 10 53 00" src="https://user-images.githubusercontent.com/4742697/59755813-8072ff00-9280-11e9-82c2-2507507b6c3a.png">

I triggered a cloud compile yesterday using this toggle, so this should produce a binary at the usual fast speed.

For C++, here's a sample CODAL application for the Brainpad:

```cpp
#include "BrainPad.h"
#include "CodalUSB.h"
#include "HIDKeyboard.h"
#include "USBJACDAC.h"
#include "JDTestService.h"

BrainPad bp;
CodalUSB usb;
USBJACDAC jacdac;
CodalDummyUSBInterface dummy;

int main()
{
    bp.init();

    usb.add(jacdac);
    usb.add(dummy);
    bp.jacdac.setBridge(&jacdac);
    usb.start();
    bp.jacdac.start();

    int state = 0;
    while(1)
    {
        bp.io.ledGreen.setDigitalValue(state);
        fiber_sleep(500);
        state = !state;
    }
}
```

To build for the trinket, you'd need to use the `codal-circuit-playground` target and adjust [the pin mappings in the model to match the trinket](https://github.com/lancaster-university/codal-circuit-playground/blob/samd-peripherals/model/CircuitPlaygroundIO.cpp). Note that you must use the `samd-peripherals` branch of `codal-circuit-playground`.

**Comment by RandoSY** [comment]
Ah, thanks so much for the crystal clear instructions. This is a perfect opportunity to upgrade my circa 1996 programming skills and toolkit. I'm especially interested in the selection of accelerometers and imu's in the "secret" dialog box, I have a use for those as well... kudos for some of the simplest usb code I've ever seen.

When I know more, I would still like to address/evaluate getting several of the 8-bt candidates talking on the wire. 

Couple of quick questions:

1. Do you know anyone outside of the ARM M0 universe that has any/plans for JACDAC?

2. Are the design files for the Brainpads residing anywhere?

**Comment by RandoSY** [comment]
Caught an this error ... under windows 10 build, python 2.7x

[181/181] Running utility command for CIRCUIT_PLAYGROUND_bin
FAILED: cmd.exe /C "cd /D C:\Codetest\ARM\codal\codal && python ./utils/uf2conv.py -o C:/Codetest/ARM/codal/codal/./CIRCUIT_PLAYGROUND.uf2 -c C:/Codetest/ARM/codal/codal/./CIRCUIT_PLAYGROUND.bin"
  File "./utils/uf2conv.py", line 32
    print "Skipping block at " + ptr + "; bad magic"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Skipping block at " + ptr + ")?
ninja: build stopped: subcommand failed.

**Comment by jamesadevine** [comment]
@RandoSY from root:
```
cd librariest/codal-circuit-playground
git checkout samd-peripherals
cd ../..
python build.py -c
```
 
> 1. Do you know anyone outside of the ARM M0 universe that has any experience/plans for JACDAC?

As you can tell, we're not yet shouting from the rooftops about JACDAC, so we're not working with anyone external directly, although internally we have experience and plans for PIC and smaller MCUs. 

> 2. Is this the Brainpad you're referring too?
>    https://brainpad.com/

Yes, I'm referring to the brainpad arcade!

**Comment by RandoSY** [comment]
Tiny typo above (for those who come after) "libariest" is libraries ... 

Caught and error after enforcing samd-peripherals.

[ 82%] Building CXX object libraries/codal-samd/CMakeFiles/codal-samd.dir/src/SAMDTCTimer.cpp.o
In file included from /home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/src/SAMDTCTimer.cpp:1:0:
/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/inc/SAMDTCTimer.h:4:27: fatal error: **LowLevelTimer.h: No such file or directory**
 #include "LowLevelTimer.h"
                           ^
compilation terminated.
libraries/codal-samd/CMakeFiles/codal-samd.dir/build.make:702: recipe for target 'libraries/codal-samd/CMakeFiles/codal-samd.dir/src/SAMDTCTimer.cpp.o' failed
make[2]: *** [libraries/codal-samd/CMakeFiles/codal-samd.dir/src/SAMDTCTimer.cpp.o] Error 1

I wonder if the downloaded asf4  prereq is missing something?

**Comment by jamesadevine** [comment]
@RandoSY thanks, edited!

Ah, I guess the original "install" checked out incompatible versions of codal-core! All that's required (i think) is:

```
cd libraries/codal-core
git checkout master
cd ../..
python build.py -c
```

**Comment by RandoSY** [comment]
I applied above, only got to 62% this time ... Sorry about spaghetti dump. 

In file included from /home/rasyoung/Codetest/ARM/codal/libraries/codal-core/source/driver-models/CodalUSB.cpp:25:0:
/home/rasyoung/Codetest/ARM/codal/libraries/codal-core/source/driver-models/CodalUSB.cpp: In member function 'void CodalUSB::initEndpoints()':
/home/rasyoung/Codetest/ARM/codal/libraries/codal-core/source/driver-models/CodalUSB.cpp:610:22: warning: comparison is always true due to limited range of data type [-Wtype-limits]
         usb_assert(0 <= info->allocateEndpoints && info->allocateEndpoints <= 2);
                      ^
/home/rasyoung/Codetest/ARM/codal/libraries/codal-core/./inc/driver-models/CodalUSB.h:307:11: note: in definition of macro 'usb_assert'
     if (!(cond))                                                                                   \
           ^
/home/rasyoung/Codetest/ARM/codal/libraries/codal-core/source/driver-models/Serial.cpp:862:6: warning: #warning define API for pin swap... [-Wcpp]
     #warning define API for pin swap...
      ^
/tmp/ccYDOnp8.s: Assembler messages:
/tmp/ccYDOnp8.s:1862: Error: lo register required -- `sub r1,r1,#5'
/tmp/ccYDOnp8.s:1863: Error: cannot honor width suffix -- `sub r1,r1,r6'
/tmp/ccYDOnp8.s:1869: Error: cannot honor width suffix -- `mov r0,#0'
/tmp/ccYDOnp8.s:1918: Error: lo register required -- `add r2,r2,#8'
/tmp/ccYDOnp8.s:1924: Error: cannot honor width suffix -- `mov r3,#10'
/tmp/ccYDOnp8.s:1935: Error: cannot honor width suffix -- `mov r0,#240'
/tmp/ccYDOnp8.s:1943: Error: cannot honor width suffix -- `mov r2,#240'
/tmp/ccYDOnp8.s:1952: Error: cannot honor width suffix -- `mov r1,#0'
/tmp/ccYDOnp8.s:1958: Error: cannot honor width suffix -- `mov r3,#0'
/tmp/ccYDOnp8.s:1960: Error: cannot honor width suffix -- `mov r2,#0'
/tmp/ccYDOnp8.s:1964: Error: cannot honor width suffix -- `mov r3,#0'
/tmp/ccYDOnp8.s:2006: Error: cannot honor width suffix -- `mov r3,#0'
/tmp/ccYDOnp8.s:2109: Error: cannot honor width suffix -- `mul r3,r0'
/tmp/ccYDOnp8.s:2127: Error: cannot honor width suffix -- `mov r0,#0'
/tmp/ccYDOnp8.s:2151: Error: cannot honor width suffix -- `mov r3,#0'
/tmp/ccYDOnp8.s:2153: Error: cannot honor width suffix -- `adc r7,r7,r3'
/tmp/ccYDOnp8.s:2181: Error: cannot honor width suffix -- `mov r0,#0'
/tmp/ccYDOnp8.s:2219: Error: cannot honor width suffix -- `mov r3,#250'
/tmp/ccYDOnp8.s:2220: Error: cannot honor width suffix -- `lsl r3,r3,#2'
/tmp/ccYDOnp8.s:2221: Error: cannot honor width suffix -- `mul r0,r3'
libraries/codal-core/CMakeFiles/codal-core.dir/build.make:1958: recipe for target 'libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Timer.cpp.o' failed
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Timer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:254: recipe for target 'libraries/codal-core/CMakeFiles/codal-core.dir/all' failed
make[1]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jamesadevine** [comment]
That doesn't look like the correct assembler output. Can you verify that CMake is finding the right compiler? It usually prints the toolchain it has found at the beginning of a fresh compile, so run `python build.py -c` and paste the first few lines.

**Comment by RandoSY** [comment]
Sorry can't quite remember how I installed the ARM compiler this VM. Not seeing anything from 

python build.py -c

rasyoung@ssd1604:~/Codetest/ARM/codal$ python build.py -c
codal-circuit-playground is already installed
Set target: codal-circuit-playground 
Using target-locked.json
Targeting codal-circuit-playground
-- Adding library path: (/home/rasyoung/Codetest/ARM/codal/libraries)
Installing dependencies...
codal-core is already installed
codal-samd is already installed
Using library: codal-circuit-playground
Using library: codal-core
Using library: codal-samd
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rasyoung/Codetest/ARM/codal/build

**Comment by RandoSY** [comment]
rasyoung@ssd1604:~/Codetest/ARM/codal$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jamesadevine** [comment]
Maybe this docker file will help? https://hub.docker.com/r/jamesadevine/codal-toolchains/dockerfile

It's the one I made for travis, and it seems to be happy with all current builds at the moment!

**Comment by RandoSY** [comment]
I looked at using that, but believe there was a conflict with my Virtual Box install on the Windows side. let me check it out on Linux.  Once I get the build tools happy, if I remember my yt/yotta experiments I just copy examples *.cpp into the root directory and invoke it how?

**Comment by RandoSY** [comment]
OK, upgrading the long in tooth arm compiler to the more recent ... "...2081-q2" I should think I'm close.

[ 90%] Building CXX object libraries/codal-samd/CMakeFiles/codal-samd.dir/src/SAMDPDM.cpp.o
/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/src/ZSingleWireSerial.cpp: In member function 'virtual void codal::ZSingleWireSerial::dmaTransferComplete(codal::DmaCode)':
/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/src/ZSingleWireSerial.cpp:45:19: **error: request for member 'fire' in '*((codal::ZSingleWireSerial*)this)->codal::ZSingleWireSerial::<anonymous>.codal::DMASingleWireSerial::<anonymous>.codal::SingleWireSerial::cb', which is of non-class type 'void(uint16_t) {aka void(short unsigned int)}'
         this->cb->fire(evt);**
                   ^~~~

**Comment by jamesadevine** [comment]
Super close! One last checkout I think... 

```
cd libraries/codal-samd
git checkout master
cd ../..
python build.py -c
```

Need to do some clean up of the build system at some point... sorry!

**Comment by RandoSY** [comment]
Remarkably, that was my next thing to try ... down to one simple variable declaration

In file included from /home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/src/SAMDDAC.cpp:29:0:
/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/inc/SAMDDAC.h:71:142: error: **'SAMDDAC_USE_VREFPU' was not declared in this scope**
     SAMDDAC(ZPin &pin, DataSource &source, int sampleRate = SAMDDAC_DEFAULT_FREQUENCY, uint16_t id = DEVICE_ID_SYSTEM_DAC, uint32_t refsel = SAMDDAC_USE_VREFPU);

**Comment by jamesadevine** [comment]
Instead, checkout `afbfcfbaebb847d0036fbcbe125482c71ab8854b` in `codal-samd`.

You'll also need to modify the config.json in root to:
```
{
    "target": {
        "name": "codal-circuit-playground",
        "url": "https://github.com/lancaster-university/codal-circuit-playground",
        "dev": true,
        "branch": "master",
        "type": "git",
        "test_ignore": true
    },
    "config":{
        "DEVICE_USB":1
    }
}
```

My travis build is not detecting a failure at present, I guess it checks out a known working configuration i.e. a tag! (I can't remember)

**Comment by jamesadevine** [comment]
Sorry for the faff!

**Comment by RandoSY** [comment]
Not to worry, best experience I can have. I find this git environment particularly complicated, but I guess it beats the old way I did it big time.  I'm sure that is in itself is a special art. 

git checkout afbfcfbaebb847d0036fbcbe125482c71ab8854b produced,

_rasyoung@ssd1604:~/Codetest/ARM/codal/libraries/codal-samd$ git checkout afbfcfbaebb847d0036fbcbe125482c71ab8854b
M	samd-peripherals
Note: checking out 'afbfcfbaebb847d0036fbcbe125482c71ab8854b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>_


The only *.json file I found in root, was codal.json so I  add  you new contents to that.

**Comment by RandoSY** [comment]
I just copied the contents of codal.json, to "config.json" per your instruction, no change on build, but we're close as 97% builds from command line.

**Comment by jamesadevine** [comment]
Sorry @RandoSY I meant `codal.json`!

**Comment by jamesadevine** [comment]
Not your issue though, checkout `i2c_hack` in codal-circuit-playground! Once again, sorry. This is why I was trying to steer you towards the definitely working makecode builds 😓

**Comment by RandoSY** [comment]
So, so close now past 99% ...

libcodal-samd.a(external_interrupts.c.o): In function `EIC_Handler':
/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/samd-peripherals/samd/samd21/external_interrupts.c:80: **multiple definition of `EIC_Handler'**
libcodal-samd.a(ZPin.cpp.o):/home/rasyoung/Codetest/ARM/codal/libraries/codal-samd/src/ZPin.cpp:601: first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/CIRCUIT_PLAYGROUND.dir/build.make:98: recipe for target 'CIRCUIT_PLAYGROUND' failed
make[2]: *** [CIRCUIT_PLAYGROUND] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/CIRCUIT_PLAYGROUND.dir/all' failed
make[1]: *** [CMakeFiles/CIRCUIT_PLAYGROUND.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RandoSY** [comment]
Will take a turn on doing something creative with Docker ...

https://medium.com/@peorth/using-docker-with-virtualbox-and-windows-10-b351e7a34adc

but would like to continue on this thread if it makes sense.

**Comment by RandoSY** [comment]
I pulled your docker image jamesadevine/codal-toolchain, to docker-toolgox, could you please give me a quick how-to to run the appropriate "wrapper file" as appropriate to build code?

**Comment by jamesadevine** [comment]
Pursuing with our earlier task. Cd to codal-samd and run git submodule sync && git submodule update


James.

Sorry for typos and brevity, I’m typing this on a phone

On 19 Jun 2019, at 23:05, RandoSY <notifications@github.com<mailto:notifications@github.com>> wrote:


I pulled your docker image jamesadevine/codal-toolchain, to docker-toolgox, could you please give me a quick how-to to run the appropriate "wrapper file" as appropriate to build code?

**Comment by RandoSY** [comment]
Righteous! I need to run python build.py codal-circuit-playround once, then python build.py -c works...
:) :) :)

***

[ 98%] Linking CXX static library ../../libcodal-circuit-playground.a
[ 98%] Built target codal-circuit-playground
[ 98%] Building CXX object CMakeFiles/CIRCUIT_PLAYGROUND.dir/source/main.cpp.o
[ 99%] Linking CXX executable CIRCUIT_PLAYGROUND
[ 99%] Built target CIRCUIT_PLAYGROUND
[ 99%] converting to hex file.
[ 99%] Built target CIRCUIT_PLAYGROUND_hex
[100%] converting to bin file.
Executing post process command
Converting to uf2, output size: 114688, start address: 0x2000
Wrote 114688 bytes to /home/rasyoung/Codetest/ARM/codal/./CIRCUIT_PLAYGROUND.uf2.
[100%] Built target CIRCUIT_PLAYGROUND_bin

**Comment by RandoSY** [comment]
Thanks for your help yesterday, great job!
